version: '3.8'

services:
  database:
    image: postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'

  indigo:
    build: ./indigo
    restart: always
    env_file:
      - ./.env
    environment:
      - DJANGO_DEBUG=false
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEFAULT_FROM_EMAIL=${DJANGO_DEFAULT_FROM_EMAIL}
      - DJANGO_EMAIL_HOST=${DJANGO_EMAIL_HOST}
      - DJANGO_EMAIL_HOST_PASSWORD=${DJANGO_EMAIL_HOST_PASSWORD}
      - DJANGO_EMAIL_PORT=${DJANGO_EMAIL_PORT}
      - DJANGO_EMAIL_HOST_USER=${DJANGO_EMAIL_HOST_USER}
      - DJANGO_EMAIL_USE_TLS=${DJANGO_EMAIL_USE_TLS}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}  
      - GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID}
      - RECAPTCHA_PUBLIC_KEY={RECAPTCHA_PUBLIC_KEY}
      - RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE_KEY}
      - SUPPORT_EMAIL=${SUPPORT_EMAIL}
      - INDIGO_ORGANISATION=${INDIGO_ORGANISATION}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    command:  gunicorn --chdir /src/indigo --worker-class gevent indigo.wsgi:application -t 600 --certfile=/root/server.crt --keyfile=/root/server.key --bind=0.0.0.0:5000 --forwarded-allow-ips=* --log-file -
    expose:
      - 5000
    ports:
      - "5000:5000"
    depends_on:
      - database

volumes:
  postgres_data:
